---
files: |
  (?x)^(
    .github/sync-upstream|
    .github/workflows/sync-upstream.yml
  )$

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace

  - repo: https://github.com/cavcrosby/shellcheck-precommit.git
    rev: v0.13.0
    hooks:
      - id: shellcheck

  - repo: https://github.com/betterleaks/betterleaks.git
    rev: v1.8.1
    hooks:
      - id: betterleaks
