name: Sync with the upstream repository

on:
  schedule:
    - cron: "0 5 * * 6"
  workflow_dispatch: {}

jobs:
  sync-upstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Sync the upstream's repository contents
        run: ./.github/sync-upstream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
